#ifndef LOGSTRUCT_H
#define LOGSTRUCT_H

typedef enum {
	LOG_JOBDISTRIBUTE = 0,
	LOG_MODESELECT,
	LOG_DATABASE,
	LOG_CONFIG,
	LOG_POLLINGTHREAD,
	LOG_SISTHREAD,
	LOG_SCRIPTTHREAD,
	LOG_INTERRUPTTHREAD,
	LOG_REPORT,
	LOG_INTERRUPTCLIENTTHREAD,
	LOG_SCRIPT,
	LOG_DEVICE,
	LOG_SENDMAIL,
	LOG_INFO,
	LOG_DEBUG,
	LOG_END
}LOGTYPE;

#endif