#include "Report.h"
#include "Log.h"
#include "Database.h"
#include "Sendmail.h"
#include "Config.h"
#include "Excel.h"
#include <QThread>
#include <xlsxdocument.h>

class SQMSReport : public IReport, public QThread
{
public:
	void SetSmtpSetting(SMTPSETTING ds);
	void Start();
	void Stop();
	void Exit();
	bool IsRun();

	SQMSReport();
	~SQMSReport();

protected:
	void run();
	bool isTime();
	void GenerateReport();
	void SendMail(const TQDevItemList& itemList);
	void doExcel(const TQDevItemList& itemList);

private:
	SMTPSETTING mSS;
	ILog* pLog;
	IDatabase* pDb;
	IConfig* pCfg;
	bool isRun;
	int nState;
	QString subject;
};

IReport* CreateReport()
{
	return new SQMSReport;
}

void ReleaseReport(IReport* pReport)
{
	if (pReport)
	{
		delete pReport;
	}
}

SQMSReport::SQMSReport():isRun(false), nState(0)
{
	pLog = CreateLog();
	pDb = CreateDatabase();
	pCfg = CreateConfig();
}

SQMSReport::~SQMSReport()
{
	Stop();
	ReleaseConfig(pCfg);
	ReleaseDatabase(pDb);
	ReleaseLog(pLog);
}

void SQMSReport::Exit()
{
	isRun = false; 
	exit();
}

bool SQMSReport::IsRun()
{
	if (!isTime() && nState == 3)
		nState = 1;
	if(!isRun && nState == 1)
		return false;
	else
		return true;
}

void SQMSReport::SetSmtpSetting(SMTPSETTING ds)
{
	mSS = ds;
}

void SQMSReport::Start()
{
	if(isRun == false)
	{
		isRun = true;
		nState = 1;
		start();
	}
}

void SQMSReport::Stop()
{
	isRun = false;
	terminate();
}

void SQMSReport::run()
{
	while(isRun)
	{
		switch (nState)
		{
		case 1:
			if(isTime())
				nState = 2;
			//Only for test
			//GenerateReport();
			//-------------
			break;
		case 2:
			GenerateReport();
			nState = 3;
			break;
		case 3:
			if(!isTime())
				nState = 1;
			break;
		default:
			break;
		}
		sleep(1);
	}
}

bool SQMSReport::isTime()
{
	int tSend, t;
	QTime mTime = QTime::currentTime();
	tSend = mSS.mStartTime.hour()*3600 + mSS.mStartTime.minute()*60 + mSS.mStartTime.second();
	t = mTime.hour()*3600 + mTime.minute()*60 + mTime.second();
	if(t > (tSend - 600) && t < (tSend + 600))
		return true;
	else
		return false;
}

void SQMSReport::GenerateReport()
{
	TQDevItemList itemList;
	pDb->GetQDevList(itemList);
	if(itemList.size() > 0)
	{
		doExcel(itemList);
		SendMail(itemList);
	}
	else
	{
		pLog->Write(LOG_REPORT, tr("GenerateReport: LLAS-100 not found"));
	}
}

void SQMSReport::SendMail(const TQDevItemList& itemList)
{
	QString file = pCfg->GetDatabaseSetting().strRepPath + "/" + "LEONIS-S-QMS-TestRep-"+ itemList.at(0).strTheaterName +"-" + QDate::currentDate().toString("yyyy-MM-dd") + ".xlsx";
	QStringList files;
	files.append(file);
	QString s = "LEONIS-S-QMS-TestRep-" + itemList.at(0).strTheaterName + "-" + QDateTime::currentDateTime().toString("yyyy-MM-dd");
	//QString body = QString::fromLocal8Bit("<p>这封邮件由LEONIS S-QMS100自动发送，请勿回复。<br>This email was sent by LEONIS S-QMS100 automatically, do not reply please.</p>"
	//	"<p>关于测试数据的说明:<br>1. 亮度测试目前是以2D放映为标准测试，如果检测期间放映机通道设置不正确或3D系统的偏振片没有从镜头前移开，会对检测结果造成影响，使检测结果偏低。<br>"
	//	"2. 根据DCI的要求，放映机安装时需要校准色彩空间，保证所有影厅放映机输出的色彩空间一致，如果色彩空间设置正确，所有影厅检测到的色域坐标就是DCI所要求的标准值。呈现的结果就是所有影厅的色域坐标一致。</p>");
	QString body = QString::fromLocal8Bit("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">"
		"<HTML><HEAD><META http-equiv=Content-Type content=\"text/html; charset=gb2312\">"
		"<META content=\"MSHTML 6.00.2900.6550\" name=GENERATOR><STYLE>"
		"BLOCKQUOTE { MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px; MARGIN-LEFT: 2em	}"
		"OL { MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px }"
		"UL { MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px }"
		"DIV.FoxDiv20150326131445984163 { COLOR: #000000 }"
		"P { MARGIN-TOP: 0px; MARGIN-BOTTOM: 0px }"
		"DIV.FoxDiv20150327091325890006 { FONT-SIZE: 10.5pt; MARGIN: 10px; COLOR: #000080; LINE-HEIGHT: 1.5; FONT-FAMILY: 宋体 }"
		"BODY { FONT-SIZE: 10.5pt; COLOR: #000080; LINE-HEIGHT: 1.5; FONT-FAMILY: 宋体 }"
		"</STYLE></HEAD><BODY style=\"MARGIN: 10px\"><DIV class=FoxDiv20150327091325890006>"
		"<DIV>这封邮件由LEONIS S-QMS100自动发送，请勿回复。"
		"<DIV>This email was sent by LEONIS S-QMS100 automatically, do not reply please.</DIV>"
		"<DIV>&nbsp;</DIV>"
		"<DIV>&nbsp;</DIV>"
		"<DIV>关于测试数据的说明: <DIV>&nbsp;</DIV>"
		"<DIV>1. 亮度测试目前是以2D放映为标准测试，如果检测期间放映机通道设置不正确或3D系统的偏振片没有从镜头前移开，会对检测结果造成影响，使检测结果偏低。</DIV>"
		"<DIV style=\"COLOR: #ff0000\">建议测试时确保通道正确且3D设备移开。</DIV>"
		"<DIV>&nbsp;</DIV>"
		"<DIV>2. 根据DCI的要求，放映机安装时需要校准色彩空间，保证所有影厅放映机输出的色彩空间一致，如果色彩空间设置正确，所有影厅检测到的色域坐标就是DCI所要求的标准值。</DIV>"
		"<DIV style=\"COLOR: #ff0000\">呈现的结果就是所有影厅的色域坐标一致。</DIV></DIV>"
		"<DIV>&nbsp;</DIV>"
		"</DIV></BODY></HTML>");
	ISendmail* pMail = NULL;

	pMail = CreateSendmail();
	pMail->SetSmtpSetting(pDb->GetSmtpSetting(), (IReport*)this);
	pMail->Send(s, body, files);
	exec();
	ReleaseSendmail(pMail);
}

void SQMSReport::doExcel(const TQDevItemList& itemList)
{
	QString title = "Test Result from SQMS-100";
	QString subTitle = "Test result was generated by SQMS-100 automatically";
	QString copy = QString::fromUtf8("Copyright \xc2\xa9 LEONIS CINEMA, all rights reserved.");
	QString fileName = pCfg->GetDatabaseSetting().strRepPath + "/" + "LEONIS-S-QMS-TestRep-"+ itemList.at(0).strTheaterName +"-" + QDate::currentDate().toString("yyyy-MM-dd") + ".xlsx";
	QDate mDate = QDate::currentDate();

	Excel excel; 
	excel.setTitle(title); 
	excel.setSubTitle(subTitle); 
	excel.setCopy(copy); 
	excel.setFileName(fileName); 
	excel.setCurrentDate();
	excel.setLog(pLog);
	excel.setDb(pDb);
	excel.setTQDevItemList(itemList);
	excel.setHeader();
	excel.setTodaySPL(); 
	excel.setTodayChroma();
	excel.setTodayLuminance();
	excel.setLastSPL(); 
	excel.setLastChroma(); 
	excel.setLastLuminance();
	excel.SaveAs(fileName);

	
}


